image: maven:3.5.3-jdk-8

before_script:
- apt-get update -qq && apt-get install -y -qq openjfx
- lscpu

build:
  script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dtestfx.robot=glass -Dglass.platform=Monocle -Dmonocle.platform=Headless -Dprism.order=sw -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=sudiamanj-github -Dsonar.login=$SONAR_TOKEN
  - cp target/tunejar-1.0-jar-with-dependencies.jar TuneJar.jar
  artifacts:
    paths:
    - TuneJar.jar
