dist: xenial
language: java
jdk:
- openjdk8
git:
  depth: false
addons:
  apt:
    update: true
    packages:
    - openjfx
script: mvn clean install -Dtestfx.robot=glass -Dglass.platform=Monocle -Dmonocle.platform=Headless -Dprism.order=sw
deploy:
  provider: releases
  api_key:
    secure: h7ddGIjZk1iW0QU7lcd+6Eum7EEdKWpobP4ZM1yUfXDDf24HZA9UcS5OUxaVhEiAPeJo2h0PGXLhknxXlTRCZCibf+XzizBCvnE0yphL9KRJ5usD7z0K0VxlBkapYVx5bP7zexLTewuLUd5mjMR/DJzODhhj3x9QdzhtZpcG9Bqb+/HbpVxqtw73cyTCcyRvA4NO71yMGx4v4YzcmWigtdUscEuPSlwvxz8tUb8YDw4+L9hq1IZOwXqoAN9gTH52T/zz8OCm93z4sNBLZj4308/dATP05NavvWhiSrvKasstzSM1IqyyEiiO09q8/VkrFzutRAaJeqRV9/QHIM0Ea43f9e6WFGZA1xzhdoOjenhRhmtVMuxw39inTy15DTqKLIaaiwk/4F1hva4WNe9Oj+arfmdL+Avz/iBXox+V0CRjH/gymEuABcF2q+VV+SPv1mbwxexvD3Bdmaskj2eva634INwBYDDvkWkn1Y0PiQxpe4RjaqlWUqzLOxR3PTfAWWQju4SWgfZn0vpS2EHYaYB/E8Ht68lskRGCu2qcRJaUfhowZvGg4uh0yVYH4Tfwfzr8JTaa1388U038h4v5/NWZhH7PJeu4m2fMOXB2UaEwsygtj1copZp3CwQZjDn3O2yO3JcuZuzkHOjMvMgJNIw5E40XpaYcphYP6aKc5do=
  file:
    - "target/TuneJar.exe"
    - "target/TuneJar.jar"
  skip_cleanup: true
  on:
    repo: sudiamanj/TuneJar
    tags: true
